apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: nginx
  name: nginx-servicemonitor
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    targetPort: 9113
  selector:
    matchLabels:
      app: nginx