name: "Build and Deploy"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: 
            ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ hashFiles('package.json') }}
            npm-${{ runner.os }}-
            npm-
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Build PDF files (docker-compose)
        run: docker compose -f ./docker/docker-compose.yml up --build
        env:
          BASE_URL: "https://code.lucasbaccan.com.br"
        
      - name: Change owner of build folder
        run: sudo chown -R $USER:$USER build

      - name: Copy pdf files to build/pdf folder
        run: cp -R pdf build/pdf

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
